### ISSUE TITLE
Does YouTube Still work?

### ISSUE THREAD

**Issue by sumdog** [kulbirsaini/videocache#1]
I was looking at this project, but before I try to install it I was wondering if YouTube is still supported? From what I understand, Google now forces https redirects for all of the toobs. Does that mean this squid plugin no longer works?

**Comment by kulbirsaini** [comment]
Anything HTTPs won't work.

**Comment by hbakhtiyor** [comment]
hi @kulbirsaini, any other solutions?

**Comment by tomdwaggy** [comment]
I'm curious if there's still a way to do caching of youtube, because you can configure squid to bump ssl connections given you install the CA certificate on client machines.

**Comment by kalamchi75** [comment]
Hi Kulbir, 

I'm trying to install the plugin on our test proxy server to cache videos. My test platform is Ubuntu 16.04 LTS, with Apache2, Squid3, Python3, and webmin
when I try to install videocache using `./install.sh` , i keep hitting python dependency errors.
First I hit an issue that it can't verify netifaces module. I have rolled back to a snapshot of the server prior to installing vidoecache, installed netifaces using pip install netifaces and tried again. 
Now it complains about a different module. Please see below: 
```
-----------------Python Modules And Development Files-----------------
Checking setuptools...................................................Installed
Checking iniparse.....................................................Missing
Installing iniparse...................................................Success
Verifying iniparse....................................................Failed

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named iniparse
```


When I run `pip install iniparse`  I get 

`Requirement already satisfied: iniparse in /usr/local/lib/python3.5/dist-packages`

is there a way to make sure that all the required modules are installed ? a list of the modules perhaps ? 

many thanks

**Comment by kalamchi75** [comment]
These are the whole installation progress lines: 
```
Checking root access..................................................Granted


---------------------Early Stage Dependency Check---------------------
Checking which........................................................Installed


------------------------Full Dependency Check-------------------------
Checking wget.........................................................Installed
Checking tar..........................................................Installed
Checking gcc..........................................................Installed
Checking python.......................................................Installed
Checking make.........................................................Installed
Checking python-pip...................................................Installed
Checking squid........................................................Installed
Checking Apache.......................................................Installed


-----------------Python Modules And Development Files-----------------
Checking setuptools...................................................Installed
Checking iniparse.....................................................Missing
Installing iniparse...................................................Success
Verifying iniparse....................................................Failed

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named iniparse

```
