### ISSUE TITLE
Python modules errors

### ISSUE THREAD

**Issue by kalamchi75** [kulbirsaini/videocache#2]
Hi, 

Hi Kulbir,

I'm trying to install the plugin on our test proxy server to cache videos. My test platform is Ubuntu 16.04 LTS, with Apache2, Squid3, Python3, and webmin
when I try to install videocache using ./install.sh , i keep hitting python dependency errors.
First I hit an issue that it can't verify netifaces module. I have rolled back to a snapshot of the server prior to installing vidoecache, installed netifaces using pip install netifaces and tried again.
Now it complains about a different module. Please see below:

```
-----------------Python Modules And Development Files-----------------
Checking setuptools...................................................Installed
Checking iniparse.....................................................Missing
Installing iniparse...................................................Success
Verifying iniparse....................................................Failed

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named iniparse
```

When I run pip install iniparse I get

Requirement already satisfied: iniparse in /usr/local/lib/python3.5/dist-packages

I also hit the same issue with `concurrentloghandler` , and I rolled back to an earlier snapshot and installed it. 

```
 pip3 install concurrentloghandler
Requirement already satisfied: concurrentloghandler in /usr/local/lib/python3.5/dist-packages
```

Yet i'm still getting the same error that videocache installer can't verify the module. Full installation progress below: 

```
./install.sh
Checking root access..................................................Granted


---------------------Early Stage Dependency Check---------------------
Checking which........................................................Installed


------------------------Full Dependency Check-------------------------
Checking wget.........................................................Installed
Checking tar..........................................................Installed
Checking gcc..........................................................Installed
Checking python.......................................................Installed
Checking make.........................................................Installed
Checking python-pip...................................................Installed
Checking squid........................................................Installed
Checking Apache.......................................................Installed


-----------------Python Modules And Development Files-----------------
Checking setuptools...................................................Installed
Checking iniparse.....................................................Installed
Checking netifaces....................................................Installed
Checking cloghandler..................................................Missing
Installing ConcurrentLogHandler.......................................Success
Verifying cloghandler.................................................Failed

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cloghandler

```

some help please ? 

Thanks

**Comment by maximlomans** [comment]
Squid3 is not compatible with Videocache is it stated in docs , 2.6.21 or later but not 3.x  :( 
also python3 isn't exactly the version of python it was aimed at ..all in the docs : 'https://cachevideos.com/documentation/software-dependencies'
